CREATE TABLE IF NOT EXISTS ADMISSAO_ABRIL (
    MATRICULA INTEGER,
    ADMISSAO DATE,
    CARGO TEXT,
    UNNAMED_3 TEXT
);
CREATE TABLE IF NOT EXISTS AFASTAMENTOS (
    MATRICULA INTEGER,
    DESC_SITUACAO TEXT,
    NA_COMPRA NUMERIC,
    UNNAMED_3 TEXT
);
CREATE TABLE IF NOT EXISTS APRENDIZ (
    MATRICULA INTEGER,
    TITULO_DO_CARGO TEXT
);
CREATE TABLE IF NOT EXISTS ATIVOS (
    MATRICULA INTEGER,
    EMPRESA INTEGER,
    TITULO_DO_CARGO TEXT,
    DESC_SITUACAO TEXT,
    SINDICATO TEXT
);
CREATE TABLE IF NOT EXISTS BASE_DIAS_UTEIS (
    SINDICATO TEXT,
    UF TEXT,
    DIAS INTEGER
);
CREATE TABLE IF NOT EXISTS BASE_SINDICATO_X_VALOR (
    UF TEXT,
    ESTADO TEXT,
    VALOR NUMERIC
);
CREATE TABLE IF NOT EXISTS DESLIGADOS (
    MATRICULA INTEGER,
    DATA_DEMISSAO DATE,
    COMUNICADO_DE_DESLIGAMENTO TEXT
);
CREATE TABLE IF NOT EXISTS ESTAGIO (
    MATRICULA INTEGER,
    TITULO_DO_CARGO TEXT,
    NA_COMPRA TEXT
);
CREATE TABLE IF NOT EXISTS EXTERIOR (
    MATRICULA INTEGER,
    VALOR NUMERIC,
    UNNAMED_2 TEXT
);
CREATE TABLE IF NOT EXISTS FERIAS (
    MATRICULA INTEGER,
    DESC_SITUACAO TEXT,
    DIAS_DE_FERIAS INTEGER
);
CREATE TABLE IF NOT EXISTS MATRICULAS (
    MATRICULA INTEGER
);
